# Source: atlas-deployment/templates/atlas-mongodb-user-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-atlas-deployment-admin-mongo
  namespace: default
  labels:
    atlas.mongodb.com/type: "credentials"
    helm.sh/chart: atlas-deployment-1.0.1
    app.kubernetes.io/name: atlas-deployment
    app.kubernetes.io/instance: mongodb-atlas
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  password: "oneeF0ur"

  # Source: atlas-deployment/templates/atlas-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-atlas-atlas-deployment-secret
  namespace: default
  labels:
    atlas.mongodb.com/type: "credentials"
    helm.sh/chart: atlas-deployment-1.0.1
    app.kubernetes.io/name: atlas-deployment
    app.kubernetes.io/instance: mongodb-atlas
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    'helm.sh/hook': post-delete,pre-install,pre-upgrade
data:
    orgId: NjA5ZmI2ZTcwNGViYzAzYjU1YmQ0ZTE2
    publicApiKey: ZHJvcmF1emg=
    privateApiKey: YmY3ODU2OWQtZWZlNS00ZGI3LWIxMDUtNGJlMThiNDZmMDE3