apiVersion: v1
kind: Service
metadata:
  name: {{ include "trips-app.fullname" . }}
  labels:
    {{- include "trips-app.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "trips-app.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata: 
  name: trips-app-external
  labels: 
spec: 
  selector: {{- include "trips-app.selectorLabels" . | nindent 4 }}
  ports:
  - port: 8082
    targetPort: 80
  type: LoadBalancer