name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Publish Docker
    - name: Docker Login
      run: docker login --username=sbuzamani --email=sibusiso.zamani@euromonitor.com
    - name: Docker Push
      run: docker push sbuzamani/tripsappapi:latest 
