apiVersion: v1
kind: Service
metadata:
  name: {{ include "trips-app-db.fullname" . }}
  labels:
    {{- include "trips-app-db.labels" . | nindent 4 }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    {{- include "trips-app-db.selectorLabels" . | nindent 4 }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "trips-app-db.fullname" . }}
#   labels:
#     {{- include "trips-app-db.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "trips-app-db.selectorLabels" . | nindent 4 }}
